<a href="https://colab.research.google.com/github/qharo/googleColab/blob/master/q_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import gym
env = gym.make('FrozenLake-v0')

In [4]:
print(env.observation_space.n) #number of observations and actions
print(env.action_space.n)

16
4


In [7]:
env.reset() #resets environment

0

In [10]:
action = env.action_space.sample()
print(action)

1


In [ ]:
observation, reward, done, info = env.step(action) #performs the action and returns observation and reward and stuff

In [ ]:
env.render() #renders GUI 

In [2]:
import gym
import numpy as np
import time

env = gym.make('FrozenLake-v0')
STATES = env.observation_space.n
ACTIONS = env.action_space.n

In [3]:
Q = np.zeros((STATES, ACTIONS))
print(Q)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
EPISODES = 1000
MAX_STEPS = 100

LEARNING_RATE = 0.81
GAMMA = 0.96

epsilon = 0.9

In [6]:
rewards = []
for episode in range(EPISODES):
  state = env.reset()
  for _ in range(MAX_STEPS):
    if np.random.uniform(0,1) < epsilon:
      action = env.action_space.sample()
    else:
      action = np.argmax(Q[state,:])

    next_state, reward, done, info = env.step(action)

    Q[state,action] = Q[state, action] + LEARNING_RATE*(reward + GAMMA*np.max(Q[next_state,:]) - Q[state, action])

    state = next_state

    if done:
      rewards.append(reward)
      epsilon-=0.001
      break

print(Q)
print("Average reward", sum(rewards)/len(rewards))

[[7.66401578e-03 1.14883752e-01 7.68611183e-03 7.50504669e-03]
 [7.38640295e-03 4.25049546e-03 5.34069929e-03 7.23326870e-02]
 [6.05382641e-03 4.66750157e-03 6.88958812e-03 4.55942046e-02]
 [2.14800410e-03 5.23933918e-04 1.75937914e-03 4.27985167e-02]
 [1.91805436e-01 1.73123829e-03 4.32874917e-03 1.81922024e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.34817241e-04 1.16665258e-04 9.79050930e-04 1.42783739e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.21719148e-03 2.50557503e-03 4.00823813e-03 1.95556255e-01]
 [1.08800656e-03 3.12003458e-01 4.45084204e-03 1.31310794e-03]
 [7.54879015e-01 2.96834845e-03 1.49731645e-03 3.03086104e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.89224283e-02 1.16701285e-01 4.20746259e-01 1.53003197e-02]
 [1.53387620e-01 9.63535104e-01 3.55327683e-01 3.44257009e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000